// components/ui/Button.tsx
import React, { forwardRef, ReactNode } from "react";
import { twMerge } from "tailwind-merge";
import clsx from "clsx";

// ============================================
// BUTTON COMPONENT - Modern Design System
// ============================================

type ButtonVariant = "primary" | "secondary" | "ghost" | "danger" | "gradient" | "outline";
type ButtonSize = "sm" | "md" | "lg" | "xl";

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  children: ReactNode;
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  icon?: ReactNode;
  iconPosition?: "left" | "right";
  fullWidth?: boolean;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      children,
      variant = "primary",
      size = "md",
      loading = false,
      icon,
      iconPosition = "left",
      fullWidth = false,
      className,
      disabled,
      ...props
    },
    ref
  ) => {
    const baseStyles = clsx(
      "inline-flex items-center justify-center gap-2",
      "font-medium rounded-xl",
      "transition-all duration-200 ease-out",
      "focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2",
      "disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none",
      fullWidth && "w-full"
    );

    const variantStyles: Record<ButtonVariant, string> = {
      primary: clsx(
        "bg-gradient-to-r from-pink-500 to-pink-600",
        "text-white shadow-sm",
        "hover:from-pink-600 hover:to-pink-700 hover:shadow-md hover:-translate-y-0.5",
        "active:translate-y-0 active:shadow-sm",
        "focus-visible:ring-pink-500"
      ),
      gradient: clsx(
        "bg-gradient-to-r from-pink-500 to-fuchsia-500",
        "text-white shadow-lg",
        "hover:opacity-90 hover:shadow-xl hover:-translate-y-0.5",
        "active:translate-y-0",
        "focus-visible:ring-pink-500"
      ),
      secondary: clsx(
        "bg-white dark:bg-slate-800",
        "text-slate-700 dark:text-slate-200",
        "border border-slate-200 dark:border-slate-700",
        "shadow-sm",
        "hover:bg-slate-50 dark:hover:bg-slate-700 hover:border-slate-300 dark:hover:border-slate-600",
        "focus-visible:ring-slate-500"
      ),
      ghost: clsx(
        "bg-transparent",
        "text-slate-600 dark:text-slate-300",
        "hover:bg-slate-100 dark:hover:bg-slate-800",
        "focus-visible:ring-slate-500"
      ),
      outline: clsx(
        "bg-transparent",
        "text-pink-600 dark:text-pink-400",
        "border-2 border-pink-500 dark:border-pink-400",
        "hover:bg-pink-50 dark:hover:bg-pink-500/10",
        "focus-visible:ring-pink-500"
      ),
      danger: clsx(
        "bg-gradient-to-r from-red-500 to-red-600",
        "text-white shadow-sm",
        "hover:from-red-600 hover:to-red-700 hover:shadow-md",
        "focus-visible:ring-red-500"
      ),
    };

    const sizeStyles: Record<ButtonSize, string> = {
      sm: "px-3 py-1.5 text-xs",
      md: "px-4 py-2 text-sm",
      lg: "px-5 py-2.5 text-base",
      xl: "px-6 py-3 text-lg",
    };

    const iconSizeStyles: Record<ButtonSize, string> = {
      sm: "w-3.5 h-3.5",
      md: "w-4 h-4",
      lg: "w-5 h-5",
      xl: "w-6 h-6",
    };

    return (
      <button
        ref={ref}
        disabled={disabled || loading}
        className={twMerge(
          baseStyles,
          variantStyles[variant],
          sizeStyles[size],
          className
        )}
        {...props}
      >
        {loading ? (
          <>
            <svg
              className={clsx("animate-spin", iconSizeStyles[size])}
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              />
              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              />
            </svg>
            <span>Loading...</span>
          </>
        ) : (
          <>
            {icon && iconPosition === "left" && (
              <span className={iconSizeStyles[size]}>{icon}</span>
            )}
            {children}
            {icon && iconPosition === "right" && (
              <span className={iconSizeStyles[size]}>{icon}</span>
            )}
          </>
        )}
      </button>
    );
  }
);

Button.displayName = "Button";

export default Button;
export { Button };
export type { ButtonProps, ButtonVariant, ButtonSize };

// app/components/ui/Button.vue
<script setup lang="ts">
import { IconRotateClockwise } from '@tabler/icons-vue';
import type { Component } from 'vue';

type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
type ButtonSize = 'sm' | 'md' | 'lg';

interface ButtonProps {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  icon?: Component;
  iconSrc?: string;
  href?: string;
  iconOnly?: boolean;
  ariaLabel?: string;
  type?: 'button' | 'submit' | 'reset';
  disabled?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'ghost',
  size: 'md',
  loading: false,
  iconOnly: false,
  type: 'button',
  disabled: false,
});

const variants: Record<ButtonVariant, string> = {
  primary: [
    'border border-ctp-instance',
    'bg-ctp-instance',
    'text-ctp-instance-text',
    'shadow-sm',
    'hover:border-ctp-instance-secondary',
    'hover:bg-ctp-instance-secondary',
    'hover:shadow-lg',
  ].join(' '),

  secondary: [
    'border border-ctp-surface1',
    'bg-ctp-surface0/70',
    'backdrop-blur-sm',
    'text-ctp-text',
    'shadow-sm',
    'hover:border-ctp-surface2',
    'hover:bg-ctp-surface1',
    'hover:shadow-lg',
  ].join(' '),

  ghost: [
    'border border-transparent',
    'bg-transparent',
    'text-ctp-subtext1',
    'hover:bg-ctp-surface0',
    'hover:text-ctp-text',
  ].join(' '),

  danger: [
    'border border-ctp-red',
    'bg-ctp-red',
    'text-ctp-base',
    'shadow-sm',
    'hover:bg-ctp-maroon',
    'hover:border-ctp-maroon',
    'hover:shadow-lg',
  ].join(' '),
};

const sizes: Record<ButtonSize, string> = {
  sm: 'min-h-9 px-3 text-sm',
  md: 'min-h-10 px-4 text-sm',
  lg: 'min-h-12 px-5 text-base',
};

const iconSizes: Record<ButtonSize, string> = {
  sm: 'h-4 w-4',
  md: 'h-5 w-5',
  lg: 'h-6 w-6',
};

const isDisabled = computed(() => props.disabled || props.loading);

const buttonClass = computed(() =>
  [
    'group',
    'inline-flex',
    'items-center',
    'justify-center',
    props.iconOnly ? 'aspect-square p-0' : props.size === 'lg' ? 'gap-2' : 'gap-1.5',
    'rounded-xl',
    'font-medium',
    'leading-none',
    'select-none',
    'whitespace-nowrap',
    'cursor-pointer',
    'touch-manipulation',
    'transition-all',
    'duration-150',
    'ease-out',
    'motion-safe:hover:-translate-y-0.5',
    'motion-safe:active:translate-y-0',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-ctp-instance/70',
    'focus-visible:ring-offset-2',
    'focus-visible:ring-offset-ctp-crust',
    'disabled:pointer-events-none',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
    'disabled:saturate-50',
    'disabled:shadow-none',
    'disabled:translate-y-0',
    props.iconOnly
      ? sizes[props.size]
          .split(' ')
          .filter((x) => x.startsWith('min-h'))
          .join(' ')
      : sizes[props.size],
    variants[props.variant],
    props.class,
  ]
    .filter(Boolean)
    .join(' '),
);

const iconClass = computed(() => iconSizes[props.size]);
</script>

<template>
  <NuxtLink
    v-if="href"
    :to="href"
    :class="buttonClass"
    :aria-label="iconOnly ? ariaLabel : undefined"
    :aria-disabled="isDisabled || undefined"
    :tabindex="isDisabled ? -1 : undefined"
  >
    <span
      v-if="loading || icon || iconSrc"
      class="inline-flex shrink-0 items-center justify-center leading-none"
    >
      <Transition
        enter-active-class="transition duration-150"
        enter-from-class="opacity-0 scale-90"
        enter-to-class="opacity-100 scale-100"
        leave-active-class="transition duration-100"
        leave-from-class="opacity-100 scale-100"
        leave-to-class="opacity-0 scale-90"
      >
        <IconRotateClockwise
          v-if="loading"
          :class="[iconClass, 'animate-spin']"
          aria-hidden="true"
        />

        <NuxtImg
          v-else-if="iconSrc"
          :src="iconSrc"
          alt=""
          :class="iconClass"
          :width="24"
          :height="24"
        />

        <component :is="icon" v-else-if="icon" :class="iconClass" aria-hidden="true" />
      </Transition>
    </span>

    <span v-if="!iconOnly" class="inline-flex items-center leading-none">
      <slot />
    </span>
  </NuxtLink>

  <button
    v-else
    :type="type"
    :disabled="isDisabled"
    :class="buttonClass"
    :aria-label="iconOnly ? ariaLabel : undefined"
    :aria-busy="loading || undefined"
  >
    <span
      v-if="loading || icon || iconSrc"
      class="inline-flex shrink-0 items-center justify-center leading-none"
    >
      <Transition
        enter-active-class="transition duration-150"
        enter-from-class="opacity-0 scale-90"
        enter-to-class="opacity-100 scale-100"
        leave-active-class="transition duration-100"
        leave-from-class="opacity-100 scale-100"
        leave-to-class="opacity-0 scale-90"
      >
        <IconRotateClockwise
          v-if="loading"
          :class="[iconClass, 'animate-spin']"
          aria-hidden="true"
        />

        <NuxtImg
          v-else-if="iconSrc"
          :src="iconSrc"
          alt=""
          :class="iconClass"
          :width="24"
          :height="24"
        />

        <component :is="icon" v-else-if="icon" :class="iconClass" aria-hidden="true" />
      </Transition>
    </span>

    <span v-if="!iconOnly" class="inline-flex items-center leading-none">
      <slot />
    </span>
  </button>
</template>
